version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/apps
hooks:
  ApplicationStart:
    - location: liar-game/liar-game-app/script/deploy.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 400
      runas: root
