@startuml
!pragma layout smetana

actor 유저 as user
participant 프론트 as fe
participant 서버 as server

title 방장의 게임 시작

autonumber
user -> fe: 게임 시작 버튼 클릭
fe --> server: 게임 생성 요청 (POST /api/game)
server --> server: 새로운 게임 생성
server --> server: 키워드 및 카테고리 결정
server --> server: 라이어 결정
server --> fe: 키워드 및 카테고리 전달
fe --> fe: 키워드 및 카테고리 화면에 출력
fe --> user: 게임 시작 완료

@enduml