@startuml
!pragma layout smetana

actor 유저 as user
participant 프론트 as fe
participant 서버 as server

title 참가자의 게임 종료

autonumber
user -> fe: 게임 종료 버튼 클릭
fe --> server: 게임 종료 요청 (DELETE /api/game)
server --> server: 게임 정보 삭제
server --> server: 라이어 확인
server --> fe: 라이어 닉네임 전달
fe --> user: 라이어 닉네임 화면에 노출

@enduml